name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }} # Add your Firebase App ID as a secret
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Firebase token for authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Use AdoptOpenJDK distribution
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Replace with your desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.5.1'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: wilzix-group
          file: build/app/outputs/apk/release/app-release.apk