name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0' # Replace with the Flutter version you want to use

      - name: Install dependencies
        run: flutter pub get

      # Add other steps as needed, such as running tests
      - name: Run tests
        run: flutter test
